name: Release

on:
  push:
    # paths:
    #  - "packages/**"
    branches:
      - master


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # This makes Actions fetch all Git history
        # so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Use Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn


    - name: Linting
      run: yarn lint

    - name: Building packages
      run: yarn build

    - name: Testing components
      run: yarn test
      env:
        CI: true

    - name: Setup CI Git User
      run: |
        git config --global user.name "imesutkoca"
        git config --global user.email "imesutkoca@gmail.com"

    - name: Create Release Pull Request
      uses: changesets/action@master
      with:
        publish: yarn release
        title: "chore(release): version packages and publish"
        commit: "chore(release): version packages"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
